### ISSUE TITLE
Symfony Exception error in Windows

### ISSUE THREAD

**Issue by usamamuneerchaudhary** [azeemhassni/pine#3]
Hi, I'm facing symfony exception error when trying to run the command "pine new <project>", Any fix for this?

**Comment by azeemhassni** [comment]
@f47a4399de1009073671a7324ba6a341d0ae38fd fixes the same. hope it will work now. Do upgrade to 2.0.2

**Comment by usamamuneerchaudhary** [comment]
Fixed, Thanks 👍
