### ISSUE TITLE
Include in generated theme functions 

### ISSUE THREAD

**Issue by marthings** [azeemhassni/pine#4]
Nice project! There is though an include in the generated theme functions.php which breaks the theme:

<?php
require_once __DIR__ . '/vendor/autoload.php';

By removing this the theme works, i just dont want to manually do it everytime i generate a new project :P. The vendor folder doesnt exist.

**Comment by azeemhassni** [comment]
Thanks for reporting,

Can you provide more information to reproduce the issue?

**Comment by marthings** [comment]
When i init a new project with:

pine new "name"

The theme doesnt work out of the box. I have to remove this include line in functions.php (sry i didnt paste it correctly in the last comment):

require_once __DIR__ . '/vendor/autoload.php';

**Comment by azeemhassni** [comment]
I tried again but can't reproduce the issue

When Pine generates theme boilerplate it also installs `timber/timber` in it which means we're 100% sure we have `vendor/autoload.php` in our theme directory.

If you still face the issue please let me know the following
- Pine version you are using
- WordPress version you selected to install
- PHP version on your machine

**Comment by azeemhassni** [comment]
due to inactivity closing this for now. If you are still facing this issue you can surely open a new one with the above mentioned required information.
