### ISSUE TITLE
Pine continues downloading after mkdir() gives Permission denied 

### ISSUE THREAD

**Issue by JunaidQadirB** [azeemhassni/pine#6]
I'm on Ubuntu 16.10 and fresh lamp install doesn't set write permissions for `/var/www/html/`.
Ideally `Pine` should either stop or prompt for password before proceeding to download.

**Comment by azeemhassni** [comment]
@JeyKeu when I tried it's showing me a readable **Permission Denied** message.

![pine-error](https://cloud.githubusercontent.com/assets/6503258/26057833/a92ba9ca-3994-11e7-83b2-a1b67ee14b01.png)

**Comment by JunaidQadirB** [comment]
I realized most users set permissions `/var/www/html/` to `writable` so I think you can close the issue.
